[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools-scm", "wheel"]

[tool.black]
line-length = 99
skip_string_normalization = "1"
target-version = ["py36", "py37", "py38"]
